baseURL = 'https://dtrac.github.io/'
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
title = "Welcome to Dan's Blog Site"
publishDir = "docs"

[params]
author = "Dan Tracey"
description = "Dan Tracey's Personal Blog Site"
keywords = "blog,developer,personal"
info = ["Azure Cloud + DevOps Engineer", "Cybersecurity", "Automation"]
avatarURL = "images/avatar.jpg"
dateFormat = "January 2, 2006"
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
favicon_32 = "/images/favicon.png"
enableEmoji = true

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/dtrac/"

[[params.social]]
name = "Gitlab"
icon = "fa fa-2x fa-gitlab"
weight = 2
url = "https://gitlab.com/dtrac/"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 3
url = "https://twitter.com/dantracey/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/dan-tracey/"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "about"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "blog"
weight = 2
url = "posts/"

#[[languages.en.menu.main]]
#name = "projects"
#weight = 3
#url = "projects/"

#[[languages.en.menu.main]]
#name = "contact"
#weight = 5
#url = "contact/"
